# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pycherwell
from pycherwell.models.save_gallery_image_request import SaveGalleryImageRequest  # noqa: E501
from pycherwell.rest import ApiException


class TestSaveGalleryImageRequest(unittest.TestCase):
    """SaveGalleryImageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveGalleryImageRequest(self):
        """Test SaveGalleryImageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pycherwell.models.save_gallery_image_request.SaveGalleryImageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
