# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pycherwell
from pycherwell.models.user_batch_save_v2_response import UserBatchSaveV2Response  # noqa: E501
from pycherwell.rest import ApiException


class TestUserBatchSaveV2Response(unittest.TestCase):
    """UserBatchSaveV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBatchSaveV2Response(self):
        """Test UserBatchSaveV2Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pycherwell.models.user_batch_save_v2_response.UserBatchSaveV2Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
