# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pycherwell
from pycherwell.models.search_item_response import SearchItemResponse  # noqa: E501
from pycherwell.rest import ApiException


class TestSearchItemResponse(unittest.TestCase):
    """SearchItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchItemResponse(self):
        """Test SearchItemResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pycherwell.models.search_item_response.SearchItemResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
