# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pycherwell
from pycherwell.models.barcode_lookup_response import BarcodeLookupResponse  # noqa: E501
from pycherwell.rest import ApiException


class TestBarcodeLookupResponse(unittest.TestCase):
    """BarcodeLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBarcodeLookupResponse(self):
        """Test BarcodeLookupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pycherwell.models.barcode_lookup_response.BarcodeLookupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
