# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pycherwell.configuration import Configuration


class BatchSaveRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'save_requests': 'list[SaveRequest]',
        'stop_on_error': 'bool'
    }

    attribute_map = {
        'save_requests': 'saveRequests',
        'stop_on_error': 'stopOnError'
    }

    def __init__(self, save_requests=None, stop_on_error=None, local_vars_configuration=None):  # noqa: E501
        """BatchSaveRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._save_requests = None
        self._stop_on_error = None
        self.discriminator = None

        if save_requests is not None:
            self.save_requests = save_requests
        if stop_on_error is not None:
            self.stop_on_error = stop_on_error

    @property
    def save_requests(self):
        """Gets the save_requests of this BatchSaveRequest.  # noqa: E501


        :return: The save_requests of this BatchSaveRequest.  # noqa: E501
        :rtype: list[SaveRequest]
        """
        return self._save_requests

    @save_requests.setter
    def save_requests(self, save_requests):
        """Sets the save_requests of this BatchSaveRequest.


        :param save_requests: The save_requests of this BatchSaveRequest.  # noqa: E501
        :type: list[SaveRequest]
        """

        self._save_requests = save_requests

    @property
    def stop_on_error(self):
        """Gets the stop_on_error of this BatchSaveRequest.  # noqa: E501


        :return: The stop_on_error of this BatchSaveRequest.  # noqa: E501
        :rtype: bool
        """
        return self._stop_on_error

    @stop_on_error.setter
    def stop_on_error(self, stop_on_error):
        """Sets the stop_on_error of this BatchSaveRequest.


        :param stop_on_error: The stop_on_error of this BatchSaveRequest.  # noqa: E501
        :type: bool
        """

        self._stop_on_error = stop_on_error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchSaveRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BatchSaveRequest):
            return True

        return self.to_dict() != other.to_dict()
