# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ClientSecuritySettingsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'internal_login_allowed': 'bool',
        'ldap_login_allowed': 'bool',
        'saml_login_allowed': 'bool',
        'windows_login_allowed': 'bool'
    }

    attribute_map = {
        'internal_login_allowed': 'internalLoginAllowed',
        'ldap_login_allowed': 'ldapLoginAllowed',
        'saml_login_allowed': 'samlLoginAllowed',
        'windows_login_allowed': 'windowsLoginAllowed'
    }

    def __init__(self, internal_login_allowed=None, ldap_login_allowed=None, saml_login_allowed=None, windows_login_allowed=None):  # noqa: E501
        """ClientSecuritySettingsResponse - a model defined in OpenAPI"""  # noqa: E501

        self._internal_login_allowed = None
        self._ldap_login_allowed = None
        self._saml_login_allowed = None
        self._windows_login_allowed = None
        self.discriminator = None

        if internal_login_allowed is not None:
            self.internal_login_allowed = internal_login_allowed
        if ldap_login_allowed is not None:
            self.ldap_login_allowed = ldap_login_allowed
        if saml_login_allowed is not None:
            self.saml_login_allowed = saml_login_allowed
        if windows_login_allowed is not None:
            self.windows_login_allowed = windows_login_allowed

    @property
    def internal_login_allowed(self):
        """Gets the internal_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501


        :return: The internal_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._internal_login_allowed

    @internal_login_allowed.setter
    def internal_login_allowed(self, internal_login_allowed):
        """Sets the internal_login_allowed of this ClientSecuritySettingsResponse.


        :param internal_login_allowed: The internal_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :type: bool
        """

        self._internal_login_allowed = internal_login_allowed

    @property
    def ldap_login_allowed(self):
        """Gets the ldap_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501


        :return: The ldap_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._ldap_login_allowed

    @ldap_login_allowed.setter
    def ldap_login_allowed(self, ldap_login_allowed):
        """Sets the ldap_login_allowed of this ClientSecuritySettingsResponse.


        :param ldap_login_allowed: The ldap_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :type: bool
        """

        self._ldap_login_allowed = ldap_login_allowed

    @property
    def saml_login_allowed(self):
        """Gets the saml_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501


        :return: The saml_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._saml_login_allowed

    @saml_login_allowed.setter
    def saml_login_allowed(self, saml_login_allowed):
        """Sets the saml_login_allowed of this ClientSecuritySettingsResponse.


        :param saml_login_allowed: The saml_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :type: bool
        """

        self._saml_login_allowed = saml_login_allowed

    @property
    def windows_login_allowed(self):
        """Gets the windows_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501


        :return: The windows_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :rtype: bool
        """
        return self._windows_login_allowed

    @windows_login_allowed.setter
    def windows_login_allowed(self, windows_login_allowed):
        """Sets the windows_login_allowed of this ClientSecuritySettingsResponse.


        :param windows_login_allowed: The windows_login_allowed of this ClientSecuritySettingsResponse.  # noqa: E501
        :type: bool
        """

        self._windows_login_allowed = windows_login_allowed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientSecuritySettingsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
