# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pycherwell.configuration import Configuration


class GridDefinition(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'grid_id': 'str',
        'name': 'str',
        'display_name': 'str'
    }

    attribute_map = {
        'grid_id': 'gridId',
        'name': 'name',
        'display_name': 'displayName'
    }

    def __init__(self, grid_id=None, name=None, display_name=None, local_vars_configuration=None):  # noqa: E501
        """GridDefinition - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._grid_id = None
        self._name = None
        self._display_name = None
        self.discriminator = None

        if grid_id is not None:
            self.grid_id = grid_id
        if name is not None:
            self.name = name
        if display_name is not None:
            self.display_name = display_name

    @property
    def grid_id(self):
        """Gets the grid_id of this GridDefinition.  # noqa: E501


        :return: The grid_id of this GridDefinition.  # noqa: E501
        :rtype: str
        """
        return self._grid_id

    @grid_id.setter
    def grid_id(self, grid_id):
        """Sets the grid_id of this GridDefinition.


        :param grid_id: The grid_id of this GridDefinition.  # noqa: E501
        :type: str
        """

        self._grid_id = grid_id

    @property
    def name(self):
        """Gets the name of this GridDefinition.  # noqa: E501


        :return: The name of this GridDefinition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GridDefinition.


        :param name: The name of this GridDefinition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def display_name(self):
        """Gets the display_name of this GridDefinition.  # noqa: E501


        :return: The display_name of this GridDefinition.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this GridDefinition.


        :param display_name: The display_name of this GridDefinition.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GridDefinition):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GridDefinition):
            return True

        return self.to_dict() != other.to_dict()
