# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SaveGalleryImageRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'base64_encoded_image_data': 'str',
        'description': 'str',
        'folder': 'str',
        'image_type': 'str',
        'name': 'str',
        'scope': 'str',
        'scope_owner': 'str',
        'stand_in_key': 'str'
    }

    attribute_map = {
        'base64_encoded_image_data': 'base64EncodedImageData',
        'description': 'description',
        'folder': 'folder',
        'image_type': 'imageType',
        'name': 'name',
        'scope': 'scope',
        'scope_owner': 'scopeOwner',
        'stand_in_key': 'standInKey'
    }

    def __init__(self, base64_encoded_image_data=None, description=None, folder=None, image_type=None, name=None, scope=None, scope_owner=None, stand_in_key=None):  # noqa: E501
        """SaveGalleryImageRequest - a model defined in OpenAPI"""  # noqa: E501

        self._base64_encoded_image_data = None
        self._description = None
        self._folder = None
        self._image_type = None
        self._name = None
        self._scope = None
        self._scope_owner = None
        self._stand_in_key = None
        self.discriminator = None

        if base64_encoded_image_data is not None:
            self.base64_encoded_image_data = base64_encoded_image_data
        if description is not None:
            self.description = description
        if folder is not None:
            self.folder = folder
        if image_type is not None:
            self.image_type = image_type
        if name is not None:
            self.name = name
        if scope is not None:
            self.scope = scope
        if scope_owner is not None:
            self.scope_owner = scope_owner
        if stand_in_key is not None:
            self.stand_in_key = stand_in_key

    @property
    def base64_encoded_image_data(self):
        """Gets the base64_encoded_image_data of this SaveGalleryImageRequest.  # noqa: E501


        :return: The base64_encoded_image_data of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._base64_encoded_image_data

    @base64_encoded_image_data.setter
    def base64_encoded_image_data(self, base64_encoded_image_data):
        """Sets the base64_encoded_image_data of this SaveGalleryImageRequest.


        :param base64_encoded_image_data: The base64_encoded_image_data of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._base64_encoded_image_data = base64_encoded_image_data

    @property
    def description(self):
        """Gets the description of this SaveGalleryImageRequest.  # noqa: E501


        :return: The description of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SaveGalleryImageRequest.


        :param description: The description of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def folder(self):
        """Gets the folder of this SaveGalleryImageRequest.  # noqa: E501


        :return: The folder of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._folder

    @folder.setter
    def folder(self, folder):
        """Sets the folder of this SaveGalleryImageRequest.


        :param folder: The folder of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._folder = folder

    @property
    def image_type(self):
        """Gets the image_type of this SaveGalleryImageRequest.  # noqa: E501


        :return: The image_type of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._image_type

    @image_type.setter
    def image_type(self, image_type):
        """Sets the image_type of this SaveGalleryImageRequest.


        :param image_type: The image_type of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["Imported", "File", "Url"]  # noqa: E501
        if image_type not in allowed_values:
            raise ValueError(
                "Invalid value for `image_type` ({0}), must be one of {1}"  # noqa: E501
                .format(image_type, allowed_values)
            )

        self._image_type = image_type

    @property
    def name(self):
        """Gets the name of this SaveGalleryImageRequest.  # noqa: E501


        :return: The name of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SaveGalleryImageRequest.


        :param name: The name of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def scope(self):
        """Gets the scope of this SaveGalleryImageRequest.  # noqa: E501


        :return: The scope of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this SaveGalleryImageRequest.


        :param scope: The scope of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._scope = scope

    @property
    def scope_owner(self):
        """Gets the scope_owner of this SaveGalleryImageRequest.  # noqa: E501


        :return: The scope_owner of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._scope_owner

    @scope_owner.setter
    def scope_owner(self, scope_owner):
        """Sets the scope_owner of this SaveGalleryImageRequest.


        :param scope_owner: The scope_owner of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._scope_owner = scope_owner

    @property
    def stand_in_key(self):
        """Gets the stand_in_key of this SaveGalleryImageRequest.  # noqa: E501


        :return: The stand_in_key of this SaveGalleryImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._stand_in_key

    @stand_in_key.setter
    def stand_in_key(self, stand_in_key):
        """Sets the stand_in_key of this SaveGalleryImageRequest.


        :param stand_in_key: The stand_in_key of this SaveGalleryImageRequest.  # noqa: E501
        :type: str
        """

        self._stand_in_key = stand_in_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SaveGalleryImageRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
