# coding: utf-8

"""
    Cherwell REST API

    Unofficial Python Cherwell REST API library.  # noqa: E501

    The version of the OpenAPI document: 9.3.2
    Contact: See AUTHORS.
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pycherwell.configuration import Configuration


class TemplateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bus_ob_id': 'str',
        'field_names': 'list[str]',
        'field_ids': 'list[str]',
        'include_all': 'bool',
        'include_required': 'bool'
    }

    attribute_map = {
        'bus_ob_id': 'busObId',
        'field_names': 'fieldNames',
        'field_ids': 'fieldIds',
        'include_all': 'includeAll',
        'include_required': 'includeRequired'
    }

    def __init__(self, bus_ob_id=None, field_names=None, field_ids=None, include_all=None, include_required=None, local_vars_configuration=None):  # noqa: E501
        """TemplateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._bus_ob_id = None
        self._field_names = None
        self._field_ids = None
        self._include_all = None
        self._include_required = None
        self.discriminator = None

        if bus_ob_id is not None:
            self.bus_ob_id = bus_ob_id
        if field_names is not None:
            self.field_names = field_names
        if field_ids is not None:
            self.field_ids = field_ids
        if include_all is not None:
            self.include_all = include_all
        if include_required is not None:
            self.include_required = include_required

    @property
    def bus_ob_id(self):
        """Gets the bus_ob_id of this TemplateRequest.  # noqa: E501


        :return: The bus_ob_id of this TemplateRequest.  # noqa: E501
        :rtype: str
        """
        return self._bus_ob_id

    @bus_ob_id.setter
    def bus_ob_id(self, bus_ob_id):
        """Sets the bus_ob_id of this TemplateRequest.


        :param bus_ob_id: The bus_ob_id of this TemplateRequest.  # noqa: E501
        :type: str
        """

        self._bus_ob_id = bus_ob_id

    @property
    def field_names(self):
        """Gets the field_names of this TemplateRequest.  # noqa: E501


        :return: The field_names of this TemplateRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_names

    @field_names.setter
    def field_names(self, field_names):
        """Sets the field_names of this TemplateRequest.


        :param field_names: The field_names of this TemplateRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_names = field_names

    @property
    def field_ids(self):
        """Gets the field_ids of this TemplateRequest.  # noqa: E501


        :return: The field_ids of this TemplateRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_ids

    @field_ids.setter
    def field_ids(self, field_ids):
        """Sets the field_ids of this TemplateRequest.


        :param field_ids: The field_ids of this TemplateRequest.  # noqa: E501
        :type: list[str]
        """

        self._field_ids = field_ids

    @property
    def include_all(self):
        """Gets the include_all of this TemplateRequest.  # noqa: E501


        :return: The include_all of this TemplateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_all

    @include_all.setter
    def include_all(self, include_all):
        """Sets the include_all of this TemplateRequest.


        :param include_all: The include_all of this TemplateRequest.  # noqa: E501
        :type: bool
        """

        self._include_all = include_all

    @property
    def include_required(self):
        """Gets the include_required of this TemplateRequest.  # noqa: E501


        :return: The include_required of this TemplateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._include_required

    @include_required.setter
    def include_required(self, include_required):
        """Sets the include_required of this TemplateRequest.


        :param include_required: The include_required of this TemplateRequest.  # noqa: E501
        :type: bool
        """

        self._include_required = include_required

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemplateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TemplateRequest):
            return True

        return self.to_dict() != other.to_dict()
